### ISSUE TITLE
plot.vt example does not work with matplotlib >= 0.98.0

### ISSUE THREAD

**Issue by VisTrailsBot** [VisTrails/VisTrails#229]
[Originally reported by emanuele]

The problem is in the 3D pipeline: axes3d.py is not supported anymore, so it raises
the error: "Uncaught exception: cannot import name unit_bbox"

I will replace that plot with a different one.
