### ISSUE TITLE
Executing workflows in batch mode is broken

### ISSUE THREAD

**Issue by rexissimus** [VisTrails/VisTrails#1103]
Executing workflows from the comand-line with `-b` generates an error after the workflow has executed.

Bisected to 10ea3ca0648e12df82444431f9f393d5ee57e659.

**Comment by rexissimus** [comment]
It looks like the spreadsheet is the only thing keeping the VistrailsApplication alive in batch mode. The global VistrailsApplication in core/application is a weakref! I am not sure how this is supposed to work.

**Comment by dakoop** [comment]
@rexissimus, what is the actual error? Could you add the stack trace?

**Comment by rexissimus** [comment]
```
Exception AttributeError: "'NoneType' object has no attribute 'startup'" in <bound method VistrailsApplicationSingleton.__del__ of <vistrails.gui.application.VistrailsApplicationSingleton object at 0x7f60c9a66b98>> ignored
Uncaught exception on initialization: TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "vistrails/run.py", line 140, in main
    app = vistrails.gui.application.get_vistrails_application()()
TypeError: 'NoneType' object is not callable
```
